from python:3.10

workdir /code

copy ./parser/requirements.txt /code/requirements.txt
run pip install --no-cache-dir -r requirements.txt

copy ./parser /code/parser

env PYTHONPATH=/code

cmd ['uvicorn', 'parser.main:app', '--host', '0.0.0.0', '--port', '8001']